### Create User

POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Luiz",
    "email": "luiz@email.com",
    "password": "0002225"
}


### Get All Users

GET  http://localhost:3003/user/getAll
Content-Type: application/json

### Create movie

POST http://localhost:3003/movie/create
Content-Type: application/json

{
    "title": "Rogue One: uma história Star Wars", 
    "description":"Ficção científica/ação",
    "durationInMinutes": 133, 
    "yearOfRelease": 2016
}